// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE6z9cjnEORcqz-PzwztFZR5UXyJGikXI',
    appId: '1:475257185913:web:b4dcea2f312ff0092f56a8',
    messagingSenderId: '475257185913',
    projectId: 'flutter-gym-app-af94d',
    authDomain: 'flutter-gym-app-af94d.firebaseapp.com',
    storageBucket: 'flutter-gym-app-af94d.appspot.com',
    measurementId: 'G-WGKMSTFL01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvXFkz3EWQIuEoADqcAQuFvknh4Zu9FK4',
    appId: '1:475257185913:android:d610211f544093a92f56a8',
    messagingSenderId: '475257185913',
    projectId: 'flutter-gym-app-af94d',
    storageBucket: 'flutter-gym-app-af94d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_4VE28cwZTaCgY34cfMh-Ybr-g4xKjHs',
    appId: '1:475257185913:ios:6309427b570967b82f56a8',
    messagingSenderId: '475257185913',
    projectId: 'flutter-gym-app-af94d',
    storageBucket: 'flutter-gym-app-af94d.appspot.com',
    iosBundleId: 'com.archit.flutterGymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_4VE28cwZTaCgY34cfMh-Ybr-g4xKjHs',
    appId: '1:475257185913:ios:b0afef621db0d39f2f56a8',
    messagingSenderId: '475257185913',
    projectId: 'flutter-gym-app-af94d',
    storageBucket: 'flutter-gym-app-af94d.appspot.com',
    iosBundleId: 'com.archit.flutterGymApp.RunnerTests',
  );
}
